const PopularTrip=[
    {
       id:1,
       title:'Bangkok',
       location:'Thailland',
       Image:require('../assets/bannkok.jpeg'),
       description:'Grand Palace, complex of buildings within walls in Bangkok, Thailand. It has been the official and ceremonial residence of the countrys kings since it was originally built in 1782.',
       duration:'7 days',
       person:4,
       rating:4.9,
       doller:'$200per/Day',
       hotelname:'Hotel Paracas',
       hotelImage:require('../assets/hotel1.jpeg'),
       hoteldescription:'hotel, building that provides lodging, meals, and other services to the traveling public on a commercial basis. A motel performs the same functions as a hotel but in a format designed for travelers using automobiles For families, hotels can say that their hotel is warm and inviting. For business travelers, hotels can say their hotel is luxurious and sophisticated.',
       hotelrevies:4.1,
       Reviews:'(24439445 Reviews)'
  
      },
    {
        id:2,
        title:'Arizona ',
        location:'United States',
        Image:require('../assets/grand.jpeg'),
        description:'Arizona is known for its varied landscapes, including deserts, mountains, and forests,The Sonoran Desert stretches from Mexico into Arizona, and the desert valleys around Phoenix and Tucson are filled with saguaro cacti.',
        duration:'5 days',
        person:3,
        rating:4.3,
        doller:'$170per/Day',
        hotelname:'The Oberoi Udaivilas',
        hotelImage:require('../assets/hotel2.jpeg'),
        hoteldescription:'hotel, building that provides lodging, meals, and other services to the traveling public on a commercial basis. A motel performs the same functions as a hotel but in a format designed for travelers using automobiles For families, hotels can say that their hotel is warm and inviting. For business travelers, hotels can say their hotel is luxurious and sophisticated. Photos ...',
        hotelrevies:4.2,
        Reviews:'(24435785 Reviews)'
     },
     {
        id:3,
        title:'Roma',
        location:'Italy',
        Image:require('../assets/roma.jpeg'),
        description:'Rome is Italys capital city and is located in the central-western part of the Italian peninsula. It s known for its rich history and culture, and is home to many famous monuments, including the Colosseum, the Pantheon and the Trevi Fountain',
        duration:'8 days',
        person:2,
        rating:4.0,
        doller:'$170per/Day',
        hotelname:'The Calile',
        hotelImage:require('../assets/hotel3.jpeg'),
        hoteldescription:'hotel, building that provides lodging, meals, and other services to the traveling public on a commercial basis. A motel performs the same functions as a hotel but in a format designed for travelers using automobiles For families, hotels can say that their hotel is warm and inviting. For business travelers, hotels can say their hotel is luxurious and sophisticated. Photos ...',
        hotelrevies:4.2,
        Reviews:'(2443544675 Reviews)'
       },
     {
        id:4,
        title:'Taj-Mahal',
        location:'India',
        Image:require('../assets/tajmahel.jpeg'),
        description:'The Taj Mahal is an ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor, Shah Jahan (reigned from 1628 to 1658)',
        duration:'6 days',
        person:3-4,
        rating:4.3,
        doller:'$205per/Day',
        hotelname:'Mount Nelson',
        hotelImage:require('../assets/hotel4.jpeg'),
        hoteldescription:'hotel, building that provides lodging, meals, and other services to the traveling public on a commercial basis. A motel performs the same functions as a hotel but in a format designed for travelers using automobiles For families, hotels can say that their hotel is warm and inviting. For business travelers, hotels can say their hotel is luxurious and sophisticated. Photos ...',
        hotelrevies:4.7,
        Reviews:'(2495445 Reviews)'
      },
     {
        id:5,
        title:'Turkey',
        location:'Turkeystan',
        Image:require('../assets/istanbul.jpeg'),
        description:'Places to visit in Turkey Includes İstanbul, Cappadocia, Pamukkale, Antalya, Ankara, Galata Tower, Istanbul Archaeological Museum, Chora Church',
        duration:'8 days',
        person:2,
        rating:4.2,
        doller:'$1400per/Day',
        hotelname:'Capella Ubud',
        hotelImage:require('../assets/hotel5.jpeg'),
        hoteldescription:'hotel, building that provides lodging, meals, and other services to the traveling public on a commercial basis. A motel performs the same functions as a hotel but in a format designed for travelers using automobiles For families, hotels can say that their hotel is warm and inviting. For business travelers, hotels can say their hotel is luxurious and sophisticated. Photos ...',
        hotelrevies:4.2,
        Reviews:'(24435245 Reviews)'
     },
     {
        id:6,
        title:'Disnylend',
        location:'Japan',
        Image:require('../assets/istanbul.jpeg'),
        description:'Disneyland is a theme park in Anaheim, California that features rides, characters, and shows based on the Disney Company creations. It s considered one of the most popular theme parks in the world',
        duration:'7 days',
        person:4,
        rating:4.9,
        doller:'$300per/Day',
        hotelname:'Kamalame Cay',
        hotelImage:require('../assets/hotel6.jpeg'),
        hoteldescription:'hotel, building that provides lodging, meals, and other services to the traveling public on a commercial basis. A motel performs the same functions as a hotel but in a format designed for travelers using automobiles',
        hotelrevies:4.1,
        Reviews:'(24498445 Reviews)'
     },
]
export default PopularTrip;